# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e597ee700a7926719d459c19b25adfbacbd2e11b990c94581fa19324f4bf4f1bf24f59cd2c7c86e3d194bd86d120f10f989bdb27d4556fc653b92f229488d18e

test:
  secret_key_base: 7f9b892f223c47fe65de464a66122511213eaee845a11497324f0827f049d24baef6de8813aef0b4eb2ed2b55a9aa54fd449ff4d2f2d8d3df39c0cb7b4906d47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
